In [1]:
pip install cryptocmd

Collecting cryptocmd
  Obtaining dependency information for cryptocmd from https://files.pythonhosted.org/packages/d6/60/ecf5636cd124e089033cede8d39d4ef842f5445ddf4ead19d49f5757be74/cryptocmd-0.6.4-py3-none-any.whl.metadata
  Downloading cryptocmd-0.6.4-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: requests in c:\users\rafael\anaconda3\lib\site-packages (from cryptocmd) (2.31.0)
Collecting tablib (from cryptocmd)
  Obtaining dependency information for tablib from https://files.pythonhosted.org/packages/cf/02/404b9a79578e1a3512bf3ae5e1fb0766859ccf3b55a83ab1e7ac4aeb7bed/tablib-3.5.0-py3-none-any.whl.metadata
  Downloading tablib-3.5.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rafael\anaconda3\lib\site-packages (from requests->cryptocmd) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rafael\anaconda3\lib\site-packages (from requests->cryptocmd) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rafael\anaconda3\lib\site-packages (from requests->cryptocmd) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rafael\anaconda3\lib\site-packages (from requests->cryptocmd) (2023.7.22)
Downloading cryptocmd-0.6.4-py3-none-any.whl (9.1 kB)
Downloading tablib-3.5.0-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.5 kB ? eta -:--:--
   ---------------------------------------- 45.5/45.5 kB 2.3 MB/s eta 0:00:00
Installing collected packages: tablib, cryptocmd
Successfully installed cryptocmd-0.6.4 tablib-3.5.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd 
import numpy as np 
import yfinance as yf 
from cryptocmd import CmcScraper
import statsmodels.api as sm

In [5]:
scraper = CmcScraper("BTC")
df = scraper.get_dataframe()
df = df.set_index("Date")
df['Close'] = pd.to_numeric(df['Close'], errors='coerce')

df

,Open,High,Low,Close,Volume,Market Cap,Time Open,Time High,Time Low,Time Close
Date,,,,,,,,,,
2024-01-15,41715.066527,43319.721183,41705.418328,42511.967720,2.232022e+10,8.332168e+11,2024-01-15T00:00:00.000Z,2024-01-15T18:47:00.000Z,2024-01-15T00:02:00.000Z,2024-01-15T23:59:59.999Z
2024-01-14,42842.263665,43065.598852,41724.613725,41796.269606,1.752143e+10,8.191599e+11,2024-01-14T00:00:00.000Z,2024-01-14T09:59:00.000Z,2024-01-14T23:55:00.000Z,2024-01-14T23:59:59.999Z
2024-01-13,42799.446488,43234.661777,42464.143204,42842.382191,2.060186e+10,8.396274e+11,2024-01-13T00:00:00.000Z,2024-01-13T08:30:00.000Z,2024-01-13T03:31:00.000Z,2024-01-13T23:59:59.999Z
2024-01-12,46354.793188,46498.134821,41903.770751,42853.166658,4.333270e+10,8.397964e+11,2024-01-12T00:00:00.000Z,2024-01-12T00:47:00.000Z,2024-01-12T22:30:00.000Z,2024-01-12T23:59:59.999Z
2024-01-11,46656.073084,48969.371400,45678.645398,46368.585382,4.583373e+10,9.086400e+11,2024-01-11T00:00:00.000Z,2024-01-11T14:52:00.000Z,2024-01-11T06:19:00.000Z,2024-01-11T23:59:59.999Z
...,...,...,...,...,...,...,...,...,...,...
2013-05-02,116.379997,125.599998,92.281898,105.209999,0.000000e+00,1.168517e+09,2013-05-02T00:00:00.000Z,2013-05-02T14:25:01.000Z,2013-05-02T14:30:02.000Z,2013-05-02T23:59:59.999Z
2013-05-01,139.000000,139.889999,107.720001,116.989998,0.000000e+00,1.298955e+09,2013-05-01T00:00:00.000Z,2013-05-01T00:15:01.000Z,2013-05-01T19:55:01.000Z,2013-05-01T23:59:59.999Z
2013-04-30,144.000000,146.929993,134.050003,139.000000,0.000000e+00,1.542813e+09,2013-04-30T00:00:00.000Z,2013-04-30T08:25:02.000Z,2013-04-30T18:55:01.000Z,2013-04-30T23:59:59.999Z
2013-04-29,134.444000,147.488007,134.000000,144.539993,0.000000e+00,1.603769e+09,2013-04-29T00:00:00.000Z,2013-04-29T13:15:01.000Z,2013-04-29T05:20:01.000Z,2013-04-29T23:59:59.999Z
2013-04-28,136.689455,143.365942,110.845593,127.954255,2.595684e+04,1.419008e+09,2013-04-28T00:00:00.000Z,2013-04-28T00:45:00.000Z,2013-04-28T13:05:00.000Z,2013-04-28T23:59:59.999Z

In [6]:
tbond10 = yf.download('IEF', "2017-01-01", "2023-12-31")['Adj Close']
tbond10 = tbond10.resample("Y").last().pct_change().dropna()
tbond10

[*********************100%%**********************]  1 of 1 completed

Date
2018-12-31    0.009877
2019-12-31    0.080295
2020-12-31    0.100067
2021-12-31   -0.033279
2022-12-31   -0.151552
2023-12-31    0.036444
Freq: A-DEC, Name: Adj Close, dtype: float64

In [7]:
df_bitcoin_anual = df.resample("Y").last()['Close'].pct_change().dropna()
df_bitcoin_anual = df_bitcoin_anual.loc[df_bitcoin_anual.index > pd.Timestamp("2017-12-31")]
df_bitcoin_anual

Date
2018-12-31   -0.735618
2019-12-31    0.922034
2020-12-31    3.031601
2021-12-31    0.596679
2022-12-31   -0.642652
2023-12-31    1.554174
2024-12-31    0.005839
Freq: A-DEC, Name: Close, dtype: float64

In [8]:
premio_risco = df_bitcoin_anual - tbond10
premio_risco.mean()

0.7807274382312105

In [11]:
retorno_esperado = tbond10.loc['2023-12-31'] + 1 *(premio_risco.mean() - tbond10.loc['2023-12-31'])

retorno_esperado

0.7807274382312105

In [12]:
scraper = CmcScraper("ETH")
df_eth = scraper.get_dataframe()
df_eth = df_eth.set_index("Date")

df_eth

,Open,High,Low,Close,Volume,Market Cap,Time Open,Time High,Time Low,Time Close
Date,,,,,,,,,,
2024-01-15,2471.666871,2550.769136,2470.820758,2511.363697,9.700630e+09,3.018177e+11,2024-01-15T00:00:00.000Z,2024-01-15T18:45:00.000Z,2024-01-15T00:02:00.000Z,2024-01-15T23:59:59.999Z
2024-01-14,2578.003740,2578.332378,2470.424323,2472.241275,9.405587e+09,2.971182e+11,2024-01-14T00:00:00.000Z,2024-01-14T00:01:00.000Z,2024-01-14T23:57:00.000Z,2024-01-14T23:59:59.999Z
2024-01-13,2522.933806,2589.079850,2498.594466,2576.597905,1.225032e+10,3.096586e+11,2024-01-13T00:00:00.000Z,2024-01-13T23:20:00.000Z,2024-01-13T01:16:00.000Z,2024-01-13T23:59:59.999Z
2024-01-12,2619.176967,2710.421941,2460.925507,2524.460148,2.362384e+10,3.033931e+11,2024-01-12T00:00:00.000Z,2024-01-12T15:12:00.000Z,2024-01-12T22:29:00.000Z,2024-01-12T23:59:59.999Z
2024-01-11,2584.171513,2687.779019,2567.993761,2619.619078,2.257525e+10,3.148323e+11,2024-01-11T00:00:00.000Z,2024-01-11T15:13:00.000Z,2024-01-11T02:11:00.000Z,2024-01-11T23:59:59.999Z
...,...,...,...,...,...,...,...,...,...,...
2015-08-11,0.708087,1.131410,0.663235,1.067860,1.463100e+06,6.456929e+07,2015-08-11T00:00:00.000Z,2015-08-11T20:39:29.000Z,2015-08-11T06:29:29.000Z,2015-08-11T23:59:59.999Z
2015-08-10,0.713989,0.729854,0.636546,0.708448,4.052830e+05,4.281836e+07,2015-08-10T00:00:00.000Z,2015-08-10T18:54:31.000Z,2015-08-10T07:34:32.000Z,2015-08-10T23:59:59.999Z
2015-08-09,0.706136,0.879810,0.629191,0.701897,5.321700e+05,4.239957e+07,2015-08-09T00:00:00.000Z,2015-08-09T06:44:29.000Z,2015-08-09T01:49:30.000Z,2015-08-09T23:59:59.999Z
2015-08-08,2.793760,2.798810,0.714725,0.753325,6.741880e+05,4.548689e+07,2015-08-08T00:00:00.000Z,2015-08-08T00:29:29.000Z,2015-08-08T19:39:30.000Z,2015-08-08T23:59:59.999Z
2015-08-07,2.831620,3.536610,2.521120,2.772120,1.643290e+05,1.666106e+08,2015-08-07T00:00:00.000Z,2015-08-07T15:09:31.000Z,2015-08-07T17:24:30.000Z,2015-08-07T23:59:59.999Z

In [13]:
df_btc = df.loc[df.index >= "2015-08-07"]
df_eth = df_eth[df_eth.index >= "2015-08-07"]

In [15]:
retorno_eth = df_eth['Close'].pct_change().dropna()
retorno_btc = df_btc['Close'].pct_change().dropna()

In [16]:
X = retorno_btc
Y = retorno_eth
X = sm.add_constant(X)
model = sm.OLS(Y, X).fit()

print(model.params[1])
print(model.rsquared)

0.9604359454307334
0.24262405307171708